Homework 1
goethesum/-go-musthave-devops-tpl pull request #5
Opened 2021-09-01 11:37 UTC by goethesum

Increment #3

2021-09-01 22:13 UTC, Barugoo commented on .github/workflows/devopstest.yml
> +name: autotests
Почему этот файл в диффах? Мб у тебя мастер неактуальный?

2021-09-01 22:15 UTC, Barugoo commented on cmd/agent/main.go
> +	timeInterval  time.Duration
Почему часть полей экспортируемые, а `timeInterval` - нет? Есть какая-то логика?

2021-09-01 22:21 UTC, Barugoo commented on internal/handlers/handlers.go
> +}
Обычно `Repository` именуют интерфейсы/структуры, которые работают с каким-то хранилищем. 
Но судя по сигнатуре методов, этот интерфейс задумывался, как нечто, что будет принимать и обрабатывать http-запросы, а это более высокий уровень логики, чем работа с хранилищем.

2021-09-01 22:31 UTC, Barugoo commented on internal/handlers/handlers.go
> +}
Для обработки запросов вместо абстрактного интерфейса лучше подойдет вполне конкретная структура (тк у тебя вряд ли будет потребность мокать функции-обработчики или подменять их реализации). В эту структуру можно, например, положить все зависимости (тот же `Repository` для работы с хранилищем), а функции-обработчики сделать ее методами.

Пример:
```go
type Server struct {
    // здесь может быть как раз таки поле *env.Env, которое у тебя выполняет роль интерфейса хранилища
}

func (s *Server) getMetrics(w http.ResponseWriter, r *http.Request) {
	key := r.URL.Query().Get("id")

	jsonMetric, err := json.Marshal(s.E.Data[key])
	if err != nil {
                log.Println(err)
		http.Error(w, "unable to unmarshal db entry", http.StatusBadRequest)
                return
	}
	w.Write(jsonMetric)
}
//...
func getRouter(s *Server) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/", s.getMetrics)
       // ....
```

2021-09-01 22:32 UTC, Barugoo commented on internal/handlers/handlers.go
> +		log.Fatalf("unable to parse the form %s", err)
Мы не используем `log.Fatal` для обработки ошибок) 
Эта функция роняет процесс, почитай документацию. 
Здесь нужно залоггировать ошибку и вернуть клиенту корректный http-ответ, после чего выйти из функции обрабочтика:
```go
	if err != nil {
                log.Println(err)
		http.Error(w, "unable to unmarshal db entry", http.StatusBadRequest)
                return
        }
```

2021-09-01 22:34 UTC, Barugoo commented on internal/handlers/handlers.go
> +	jsonMetric, err := json.Marshal(e.E.Data[key])
Ты делаешь классный потоко-безопасный метод для получения метрик по ключу `env.GetMetricsByKey`, а здесь про него забываешь и ходишь в мапку Data напрямую, рискуя словить race condition

2021-09-01 22:35 UTC, Barugoo commented on internal/handlers/handlers_test.go
> +		if tt.method == "GET" {
Я бы разделил тест-кейсы для ручек POST и GET
Тогда тест-функция получится более аккуратной и читабельной.

2021-09-01 22:37 UTC, Barugoo commented on internal/handlers/handlers_test.go
> +// 	repoMock.On("GetUserBy", "user1").Return("name", nil)
Убирай из репозитория закомментированный код, он сильно усложняет восприятие. Здесь он у тебя стоит немного в сторонке от действующего кода, но бывает такое, что наши коллеги комментируют в том числе куски реализации внутри рабочих функций. И это ужасно дизориентирует.
Если ты хочешь что-то убрать из кода - ты это удаляешь, а не комментируешь.

2021-09-01 22:38 UTC, Barugoo commented on cmd/agent/main.go
> +}
Круто, что ты вынес конфиг в отдельную структуру, но еще круче было бы, если бы ее содержимое можно было настраивать с помощью переменных окружения. Хардкод - это не гуд.

2021-09-01 22:42 UTC, Barugoo commented on cmd/agent/main.go
> +		Post(endpoint)
`Сервер должен принимать методом POST запросы, содержащие данные в стандартной кодировке URL Query парами ключ-значение`

2021-09-01 22:47 UTC, Barugoo commented on internal/env/env.go
> +
Есть вопросы к неймингу сущностей
Почему моделька метрики имеет суффикс '-Server'? Это структура описывающая модель логики, некий обьект которым ты оперируешь при обработки запроса. Она не принимает запросы и сервером не является.

Схожий вопрос к имени структуры Env. Под ENV обычно подразумевают переменные окружения, а не окружение приложения. Насколько я понял ты захотел в этой структуре хранить вообще все, что относится к твоему приложению. Но ни портом, ни методом `GetMetricsByKey` ты так и не восппользовался. Почему?

Нейминг - это очень важная часть написания программы, хороший нейминг улучшает понимание кода читающим, плохой - в лучшем случае это понимание ухудшает. В худшем приводит к неправильной доработки твоего функционала коллегами из-за того, что изначальная логика искажена плохим неймингом.

2021-09-01 22:48 UTC, Barugoo requested changes
Отправил на доработку. Много вопросов к пул-реквесту. Не все тесты пройдены

2021-09-02 16:29 UTC, Barugoo commented on cmd/server/main.go
> +
```go
// в пакете internal/env
type Env struct {
    Data map[string]env.MetricServer
    Handlers handlers.Repository
//...
}
// в пакете мейн
func main(){
        repo := handlers.NewRepository()
	e := &env.Env{
 		PortNumber: ":8080",
 		Data:       make(map[string]env.MetricServer),
                Handlers: repo,
 	}
// в функции router
mux.Get("/", e.Handlers.GetMetrics)
//...
```

2021-09-02 16:37 UTC, Barugoo commented on internal/env/env.go
> +
```go
type MetricType string

const (
    MetricTypeGauge = "gauge"
)

var a string
var b MetricValue

a = r.Form.Get()
b = MetricType(r.Form.Get())
```

2021-09-02 16:37 UTC, Barugoo commented on internal/env/env.go
> +func (e *Env) GetMetricsByKey(ctx context.Context, key string) (MetricServer, error) {
-> `(*MetricServer, error)`

когда ты делаешь ретурн при ошибке ты просто пишешь: `return nil, err`

2021-09-04 12:44 UTC, goethesum commented
Исправлены все замечания. Так же исправлена проблема запуска автотетстов, когда не загружается нужный бинарник для devopstest. Не проходят автотесты 

- Post
- Post ver2
- Monitoring data

Не совсем понятны критерии прохождения данных тестов.

2021-09-06 21:08 UTC, Barugoo commented on internal/config/config.go
> +		http.Error(w, "There are some empty keys", http.StatusBadRequest)
Когда я говорил про валидацию, я имел в виду несколько иные конструкции)
Такой свитч очень тяжело воспринимать. Еще сильнее воспринимать вот такое:
```go
cs.Storage[r.URL.Query().Get("id")] // передача вызова функции в качестве ключа мапки 
```
На мой взгляд гораздо проще читается вот такой код:
```go
id := r.URL.Query().Get("id")
cs.Storage[id]
```
 Я бы разбил процесс валидации и извлечения данных из запроса. И еще хорошая практика вынести строковые константы, которые ты используешь на постоянке в константы.
Как-то так:
```go
const (
    queryKeyMetricID = "id"
    queryKeyMetricType = "type"
    queryKeyMetricValue = "value"
)

const (
    MetricTypeGauge = "gauge"
    MetricTypeCounter = "counter"
)

func getMetricEntityFromRequest(r *http.Request) (*Metric, error) {
    m := new(Metric)

    if m.ID := r.URL.Query().Get(queryKeyMetricID); m.ID == "" {
        return nil, errors.New("empty \"id\" query param")
    }
    if m.Value := r.URL.Query().Get(queryKeyMetricValue); m.Value == "" {
        return nil, errors.New("empty \"value\" query param")
    }
    if m.Type := r.URL.Query().Get(queryKeyMetricType); m.Type == "" {
        return nil, errors.New("empty \"type\" query param")
    }
    if m.Type != MetricTypeGauge && m.Type != MetricTypeCounter {
        return nil, errors.New("unknown metric type")
    }
    // и так далее..
    return m, nil
}

func (cs *ConfigServer) PostHandlerMetrics(w http.ResponseWriter, r *http.Request) {
    m, err := getMetricEntityFromRequest(r)
    if err != nil {
        http.Error(w, err, http.StatusBadRequest)
    }
```

2021-09-06 21:13 UTC, Barugoo commented on internal/config/config.go
> +		http.Error(w, "metric not found", http.StatusBadRequest)
```
Здесь нужно залоггировать ошибку и вернуть клиенту корректный http-ответ, после чего выйти из функции обрабочтика:
```
```go
http.Error(...)
return
```

2021-09-06 21:21 UTC, Barugoo commented on internal/config/config.go
> +	w.Write(jsonMetric)
Когда у тебя есть интерфейс `io.Writer` лучше использовать:
```go
if err := json.NewEncoder(w).Encode(&value); err != nil { // передаем по указателю
    http.Error(w, "unable to marshal the struct", http.StatusBadRequest)
    return
}
```
Тк при использовании `json.Marshal` и `json.Unmarshal` ты работаешь с конечным набором байтов, который на самом деле может быть большим и копировать его в отдельную переменную прежде чем положить в ответ (`jsonMetric, err := json.Marshal(value)`) может быть дорого.

2021-09-06 21:22 UTC, Barugoo commented on internal/config/config.go
> +func (cs *ConfigServer) GetMetricsByKey(ctx context.Context, key string) (metric.Metric, error) {
Опять процитирую себя:
```
-> (*MetricServer, error)

когда ты делаешь ретурн при ошибке ты просто пишешь: return nil, err
```

2021-09-06 21:23 UTC, Barugoo commented on internal/config/config.go
> +		return metric.Metric{}, errors.New("metric not found")
Опять процитирую себя по поводу возвращаемых значений:
```
-> (*MetricServer, error)

когда ты делаешь ретурн при ошибке ты просто пишешь: return nil, err
```

2021-09-06 21:25 UTC, Barugoo commented on internal/config/config.go
> +		http.Error(w, "value is empty", http.StatusBadRequest)
Давай вынесем валидацию в отдельную функцию

2021-09-06 21:27 UTC, Barugoo requested changes
Добавил комментарии по небольшим моментам. В целом круто, но тесты по второму и третьему инкременту не все зеленые, надо поправить)

2021-10-11 06:25 UTC, Barugoo commented on cmd/agent/main.go
> +		log.Printf("error during marshaling in MetricSend %s", err)
А есть ли нам смысл дальше выполнять функцию, если здесь произошла ошибка? 
Я бы сделал: 
```go
if err != nil {
        return nil, fmt.Errorf("error during marshaling in MetricSend %w", err)
}
```
А логгировал бы уже ошибку в том месте, где вызывается текущая функция

2021-10-11 06:26 UTC, Barugoo commented on cmd/agent/main_test.go
> +	assert.Equal(t, 200, resp.StatusCode())
`200` -> `http.StatusOK`

2021-10-11 06:28 UTC, Barugoo commented on cmd/server/main.go
> +		return
Давай ради единообразия сделаем здесь `log.Fatal`

2021-10-11 06:29 UTC, Barugoo commented on cmd/server/main.go
> +		fmt.Printf("%+v\n", err)
Здесь тоже `log.Fatal` будет корректно

2021-10-11 06:29 UTC, Barugoo commented on cmd/server/main.go
> +		fmt.Printf("%+v\n", err)
Можно еще залоггировать получившийся конфиг кстати

2021-10-11 06:30 UTC, Barugoo commented on internal/config/config.go
> +	PortNumber  string `env:"ADDRESS" envDefault:"0.0.0.0:8080"`
Это скорее все же `Address`, а не `PortNumber`
Собсна ты его и используешь как адрес когда сервер стартуешь

2021-10-11 06:31 UTC, Barugoo commented on internal/config/config.go
> +	Storage     map[string]metric.Metric
Мне кажется сторедж нужно вынести в отдельную структуру Service, например
Он логически не является частью конфига

2021-10-11 06:33 UTC, Barugoo commented on internal/config/config.go
> +	}
Ты здесь используешь непопулярную форму конструкции switch, которая работает как эквивалент if-else
Лучше вот так:
```go
switch met.Type {
case metric.MetricTypeGauge:
//...
case metric.MetricTypeCounter:
//...
}
```

2021-10-11 06:33 UTC, Barugoo commented on internal/config/config.go
> +		http.Error(w, "not found", http.StatusNotFound)
Здесь ретурн

2021-10-11 06:40 UTC, Barugoo requested changes
Все очень хорошо, один нюанс архитектурный - разнеси плс структуру ConfigServer на ConfigServer и Server/Service
В первой будет хранится непосредственно конфиг для запуска который ты парсишь из переменных окружения, после чего либо отбрасываешь, либо добавляешь в виде поля по значению в структуру Service (чтобы из логики потом обращаться к значениям конфига если это нужно)
А во второй у тебя будет хранится стейт твоего сервиса (Storage, Config) и методы сервиса (http-хэндлеры)

2021-10-28 11:08 UTC, merged